---
 - name: Installatin and starting of tomcat
   hosts: all
   become: yes
   vars:
    java_ver: java-11-openjdk
    java_version: java
    alternative_path1: java-11-openjdk-11.0.18.0.10-3.el9.x86_64
    alternative_path2: java-1.8.0-openjdk-1.8.0.402.b06-1.el7_9.x86_64
    tomcat_version: 8.5.98
    tomcat_port: 8090


   tasks:
    - name: Updating all packages
      yum:
        name: "*"
        state: latest

    - name: Installing Java packages
      yum: 
        name: "{{ java_ver }}"
        state: present
      when: ansible_distribution_major_version == "9"

    - name: Installing java package on Linux 7
      yum: 
        name: "{{ java_version }}"
        state: present
      when: ansible_distribution_major_version == "7"

    - name: Set Alternative for java
      alternatives: 
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/{{ alternative_path1 }}/bin/java
      when: ansible_distribution_major_version == "9"   
      
    - name: Set Alternative for java
      alternatives: 
        name: java
        link: /bin/java
        path: /usr/lib/jvm/{{ alternative_path2 }}/jre/bin/java
      when: ansible_distribution_major_version == "7"

    - name: Delete the existing tomcat tar file of this version
      command: rm -rf /usr/local/apache-tomcat-{{ tomcat_version }}.tar.gz
      ignore_errors: yes

    - name: Delete the tomcat file
      command: rm -rf /usr/local/apache-tomcat-{{ tomcat_version }} && rm -rf /usr/local/tomcat
      ignore_errors: yes

    - name: Download Tomcat 
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: /usr/local/

    - name: Extract the Tomcat 
      unarchive:
        src: /usr/local/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: Rename the tomcat file
      command: mv /usr/local/apache-tomcat-{{ tomcat_version }} /usr/local/tomcat 
 
    - name: Configuring tomcat port
      template:
        src: server.xml.j2
        dest: /usr/local/tomcat/conf/server.xml

    - name: Start Tomcat
      shell: nohup /usr/local/tomcat/bin/startup.sh &




