---
- name: NTPD service 
  hosts: all
  tasks: 
    - name: "PRELIM | Check for ntpd service"
      ansible.builtin.systemd:
          name: "ntpd"
      register: ntpd_service

    - debug:
       var: ntpd_service.status.ActiveState 
