---
- name: This playbook will clear the cache yum and delete the file
  command: yum clean all
  args:
     warn: false
  async: 60
  poll: 5
  become: true
  changed_when: true

- name: Delete the /var/cache/yum/ file
  file:
    path: /var/cache/yum
    state: absent
  become: true
