---
- name: Ensure cramfs file system is disabled
  hosts: all
  become: true
  gather_facts: false
  vars:
    modeprobe: "/etc/modprobe.d/cis.conf"
  tasks:
    - name: Check if modprobe file exists
      stat:
        path: "{{ modeprobe }}"
      register: modprobe

    - name: Check if the cramfs file system in disable
      command: modprobe -n -v cramfs
      register: mode_cramfs
      check_mode: false
      changed_when: mode_cramfs.stdout is search('cramfs')


    - name: Check if cramfs is loaded
      command: lsmod
      register: lsmod
      check_mode: false
      changed_when: lsmod.stdout is search('cramfs')

    - name: Unload the cramfs if loaded
      command: modprobe -r cramfs
      register: modprobe_remove
      when: lsmod.stdout is search('cramfs.*')

    - name: Ensure cramfs file system is disable
      lineinfile:
        dest: "{{ modeprobe }}"
        regexp: "^install cramfs"
        line: "install cramfs /bin/true"
        state: present
      when: modeprobe.stat.exists is defined and  modeprobe.stat.exists 

              

