---
- name: Ensure IP Forward is disabled 
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure ip forward is disabled
      sysctl:
          name: net.ipv4.ip_forward
          value: 0
          reload: yes
          sysctl_set: yes
          state: present
          ignoreerrors: yes

