---
- name: Ensure use of privileged commands is collected
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure use of privileged commands is collected
      shell: find / -xdev \( -perm -4000 -o -perm -2000 \) -type f | awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged" }'
      register: prive_output
      changed_when: false

    - name: Ensure priviledge command added in audit.rules files
      lineinfile:
        path: /etc/audit/audit.rules
        line: "{{ item }}"
        state: present
        backup: yes
      with_items: "{{ prive_output.stdout_lines }}"

