---
 - name: Install  package
   yum: 
     name: "{{ package }}"
     state: latest
    
 - name: Start {{ service_name }} service
   service:
     name: "{{ service_name }}"
     state: started

       

