---
 - name: restart ntpd
   service:
     name: ntpd
     state: restarted
     enabled: yes
 - name: restart chronyd
   service:
     name: chronyd
     state: restarted
     enabled: yes



# handlers file for ntpd
